### ISSUE TITLE
Robot display - necessary and sufficient conditions

### ISSUE THREAD

**Issue by bsb808** [CCOMJHC/AutonomousMissionPlanner#4]
As a baby step, I'm trying to get a generic robot to show up in CAMP.  I'm wondering what the necessary and sufficient conditions are for the USV to be displayed.

From the CAMP getting started example (`roslaunch project11_simulation sim_local.launch'), it looks like there are position, velocity and orientation being subscribed to by CAMP (in the /ben/nav namespace).  Here is the graph
![Screenshot from 2021-07-22 08-18-58](https://user-images.githubusercontent.com/8921143/126853109-16a9f035-2ce3-4e77-a81d-c2166472c4a7.png)

I tried an example where the system only publishes the position topic...
![Screenshot from 2021-07-23 18-03-24](https://user-images.githubusercontent.com/8921143/126853148-1f1248fa-8017-4bfd-a8cf-846c1071ea6b.png)

It appears that the position publications alone are insufficient for the display to show up (I think).  What are the ROS API necessary and sufficient conditions for the robot to be  drawn in the dispay?

**Comment by bsb808** [comment]
There are also at least a couple of "heartbeat" messages being subscribed to by CAMP - with publications at 20 Hz.

* Are one or both necessary?
* Is the a minimum publication rate?
* Are there conditions on the key/value pairs that need to be included?


Heartbeat
~ 20 Hz

/ben/project11/heartbeat [marine_msgs/Heartbeat]
---
header: 
  seq: 46140
  stamp: 
    secs: 1626974317
    nsecs: 198406124
  frame_id: ''
values: 
  - 
    key: "piloting_mode"
    value: ''
  - 
    key: "sim"
    value: "asv_sim"
  - 
    key: "have_commands"
    value: "false"
Mission Manager Heartbeat
~ 20 Hz

/ben/project11/status/mission_manager [marine_msgs/Heartbeat]
---
header: 
  seq: 23795
  stamp: 
    secs: 1626974389
    nsecs: 548406124
  frame_id: ''
values: 
  - 
    key: "state"
    value: "Pause"
  - 
    key: "tasks_count"
    value: "0"
  - 
    key: "current_task"
    value: "None"
---

**Comment by apob** [comment]
Brian,

CAMP expects primary vehicle position/heading from 

- /ben/sensors/oem/position (sensor_msgs::NavSatFix)
- /ben/sensors/oem/orientation (sensor_msgs::Imu) 

and 

- /ben/nav/position (sensor_msgs::NavSatFix)
- /ben/nav/orientation" (sensor_msgs::Imu)

The "ben" portion can be overridden using the robotNamespace config variable.  Much of CAMP's ROS interface and vehicle specific drawing code is in:
https://github.com/CCOMJHC/camp/blob/noetic/src/roslink.cpp

It doesn't seem like there would be any heartbeats necessary to display a vehicle but I could easily be wrong.  I don't believe the view recenters on the vehicle so you might have to zoom way out to initially see it. 

Detail taken from the Trello card:
https://trello.com/c/zHiH4ovp

Best,
Andy

**Comment by bsb808** [comment]
Awesome.  Thank you @apob .  I'll give it a shot

**Comment by rolker** [comment]
Good detective work! Heartbeats aren't necessary, just position.
This is all changing as I update the code to support our new DriX. Instead of hard coded topics, camp will listen to a topic (defaults to /project11/platforms) where descriptions of assets to track can be published. This will remove the hard coded components that you discovered above and allow the tracking and control of multiple vehicles.

**Comment by bsb808** [comment]
This is probably more for @apob .
I had the Gazebo simulation publish position, orientation and velocity.  The pertinent part of the rosgraph is this...
![Screenshot from 2021-07-24 15-35-45](https://user-images.githubusercontent.com/8921143/126882528-ab51ccbe-0fc6-4c49-a4ff-54a4db8a403d.png)

The example setup is here: https://bitbucket.org/gfoe/project12/wiki/demo_annie_gazebo_camp


I still don't see the USV icon in the CAMP view.  I verified the the position (lat/lon) being published is such that it should show up on the map.

My next step would be to start digging into the CAMP source, but I thought if you already had an understanding of the source, then we might be more efficient to divide and conquer.

**Comment by apob** [comment]
@bsb808,

Part of the issue at least is that CAMP doesn't seem to like our geotiff.  It loads and displays it but latitude and longitude are transposed.  As far as I can tell this _might_ be from from differing "Data axis to CRS axis mapping":
https://gdal.org/tutorials/osr_api_tut.html#crs-and-axis-order

I'm basing this on differing `gdalinfo` output where the image that doesn't work reports "Data axis to CRS axis mapping: 2,1" while those that do report "Data axis to CRS axis mapping: 1,2".

I attempted to find a fix then decided discretion is the better part of valor :) and reprojected our image to UTM12N, which we'll need for Hypack anyway, and that worked as expected.  You can find this image here:
https://drive.google.com/file/d/1e_DyX4rI-OlwjawT75T8hr5gidTS_QBM/view?usp=sharing

Using "R600-YS-UTM12N-v2-meters.tif" and this:
`rostopic pub -r 10 /annie/sensors/oem/position sensor_msgs/NavSatFix '{longitude: -110.388, latitude: 44.524}'` 

I can see the boat icon right off the northern tip of Stevenson island in CAMP.

---

I followed your demo instructions here:
https://bitbucket.org/gfoe/project12/wiki/demo_annie_gazebo_camp

and the subscriptions seem to be there but `rostopic echo` didn't show anything publishing on:
- `/jacm_gps_position`
- `/annie/sensors/oem/position`
- `/annie/nav/position`

so even after I fixed the chart issue I didn't see anything on CAMP.

This problem could definitely be on my end though as ystone_camp.launch/Gazebo puts a serious hurt on development VM which could affect my results.

Best,
Andy

**Comment by rolker** [comment]
Andy, could you provide me with the geotiff that doesn't work? You could open a new issue just for this. Thanks!

**Comment by bsb808** [comment]
Thank you @apob - the projection issue was my problem.  I didn't register that lat/lon was switched, so wasn't seeing the USV.

Is there a move-view-to-vessel feature in CAMP?  If not, I'll open an issue as a nice-to-have feature.

**Comment by apob** [comment]
@bsb808 I don't believe there is a center view on vessel feature.  In the meantime zooming way out always works.

@rolker the "Look Here" and "Look at ASV" context menus are intended to control a base robotic camera correct (Johnny5 camera)?  I opened up another issue as you requested.  If there's any testing or help I can give there let me know.  I was hesitant to poke around too much without a larger stable of known working rasters.

**Comment by bsb808** [comment]
Closing as resolved by @apob with the underlay reprojection.
